# ======================== Kibana Configuration =========================
#
# This file is a complete configuration example for Kibana with comments for 
# all the different sections and settings.
#
# To use this file, copy it to `config/kibana.yml` and edit to fit your needs.
#
# For more configuration options see the configuration guide in our docs:
# https://www.elastic.co/guide/en/kibana/current/configuration.html

# ================================ Server ================================
#
# The hostname that Kibana should bind to. Set to 0.0.0.0 to bind to all interfaces.
server.host: "0.0.0.0"

# The port that Kibana should bind to.
server.port: 5601

# A human-readable display name that identifies this Kibana instance.
server.name: "ecommerce-kibana"

# The public base URL for this Kibana instance.
#server.basePath: ""

# The maximum payload size in bytes for incoming server requests.
server.maxPayload: 1048576

# ================================ Elasticsearch ================================
#
# The URLs of the Elasticsearch instances to use for all your queries.
elasticsearch.hosts: ["http://elasticsearch:9200"]

# If your Elasticsearch is protected with basic authentication, these settings provide
# the username and password that the Kibana server uses to perform maintenance on the
# Kibana index at startup. Your Kibana users still need to authenticate with Elasticsearch,
# which is proxied through the Kibana server.
#elasticsearch.username: "kibana_system"
#elasticsearch.password: "pass"

# Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
# These settings enable SSL for outgoing requests from the Kibana server to the browser.
#server.ssl.enabled: false
#server.ssl.certificate: "/path/to/your/server.crt"
#server.ssl.key: "/path/to/your/server.key"

# Optional settings that provide the paths to the PEM-format SSL certificate and key files.
# These files are used to verify the identity of Kibana to Elasticsearch and are required when
# xpack.security.http.ssl.client_authentication in Elasticsearch is set to required.
#elasticsearch.ssl.certificate: "/path/to/your/client.crt"
#elasticsearch.ssl.key: "/path/to/your/client.key"

# Optional setting that enables you to specify a path to the PEM file for the certificate
# authority for your Elasticsearch instance.
#elasticsearch.ssl.certificateAuthorities: ["/path/to/your/CA.pem"]

# To disregard the validity of SSL certificates, change this setting's value to 'none'.
#elasticsearch.ssl.verificationMode: "full"

# ================================ Logging ================================
#
# Set the logging level for Kibana.
logging.root.level: warn

# Set the verbosity of Kibana's logs.
logging.appenders:
  default:
    type: console
    layout:
      type: json

# Log queries sent to Elasticsearch. Requires logging.verbose: true.
#elasticsearch.logQueries: false

# ================================ Monitoring ================================
#
# Enable collection of Kibana usage data for Kibana monitoring purposes.
monitoring.ui.enabled: true
monitoring.kibana.collection.enabled: true

# Set to false to disable X-Pack features.
xpack.monitoring.enabled: true

# ================================ Security ================================
#
# Disable security features for development environment
xpack.security.enabled: false

# ================================ Reporting ================================
#
# Configure reporting settings
xpack.reporting.enabled: true

# ================================ Alerting ================================
#
# Configure alerting settings
xpack.alerting.enabled: true

# ================================ UI Settings ================================
#
# Configure UI settings for better user experience

# Set the default theme
#ui.theme: "dark"

# Configure the default index pattern
#kibana.defaultAppId: "discover"

# ================================ E-commerce Specific ================================
#
# Customizations for e-commerce monitoring

# Enable Canvas for custom dashboards
xpack.canvas.enabled: true

# Enable Graph for relationship analysis
xpack.graph.enabled: true

# Configure index lifecycle management
xpack.ilm.enabled: true

# Configure snapshot and restore
xpack.snapshot_restore.enabled: true

# Configure cross cluster search
xpack.ccr.enabled: false

# ================================ Data Views ================================
#
# Configure default data views for e-commerce indices
data.autocomplete.valueSuggestions.enabled: true
data.autocomplete.valueSuggestions.terminateAfter: 100000

# ================================ Advanced Settings ================================
#
# Configure memory usage
node.options: "--max-old-space-size=2048"

# Configure request timeout
elasticsearch.requestTimeout: 30000

# Configure ping timeout
elasticsearch.pingTimeout: 3000

# Configure the number of milliseconds to wait before retrying a failed request to Elasticsearch
elasticsearch.requestHeadersWhitelist: ["authorization"] 